import { PERMISSIONS, ROLES } from "./permissions.js";

// ==========================================================
// SUPER ADMIN
// ==========================================================

const SUPER_ADMIN_PERMISSIONS = Object.values(PERMISSIONS);

// ==========================================================
// ORGANIZATION ADMIN
// ==========================================================

const ORG_ADMIN_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.ORGANIZATION_VIEW,
  PERMISSIONS.ORGANIZATION_UPDATE,

  PERMISSIONS.USER_VIEW,
  PERMISSIONS.USER_CREATE,
  PERMISSIONS.USER_UPDATE,
  PERMISSIONS.USER_DELETE,
  PERMISSIONS.USER_STATUS_UPDATE,
  PERMISSIONS.USER_ROLE_UPDATE,

  PERMISSIONS.ROLE_VIEW,
  PERMISSIONS.ROLE_CREATE,
  PERMISSIONS.ROLE_UPDATE,
  PERMISSIONS.ROLE_DELETE,

  PERMISSIONS.PERMISSION_VIEW,
  PERMISSIONS.PERMISSION_ASSIGN,

  PERMISSIONS.NCR_VIEW,
  PERMISSIONS.NCR_CREATE,
  PERMISSIONS.NCR_UPDATE,
  PERMISSIONS.NCR_DELETE,
  PERMISSIONS.NCR_STATUS_UPDATE,

  PERMISSIONS.CAPA_VIEW,
  PERMISSIONS.CAPA_CREATE,
  PERMISSIONS.CAPA_UPDATE,
  PERMISSIONS.CAPA_DELETE,
  PERMISSIONS.CAPA_STATUS_UPDATE,
  PERMISSIONS.CAPA_ASSIGN,

  PERMISSIONS.AUDIT_VIEW,
  PERMISSIONS.AUDIT_CREATE,
  PERMISSIONS.AUDIT_UPDATE,
  PERMISSIONS.AUDIT_DELETE,

  PERMISSIONS.DOCUMENT_VIEW,
  PERMISSIONS.DOCUMENT_CREATE,
  PERMISSIONS.DOCUMENT_UPDATE,
  PERMISSIONS.DOCUMENT_DELETE,
  PERMISSIONS.DOCUMENT_APPROVE,
  PERMISSIONS.DOCUMENT_STATUS_UPDATE,

  PERMISSIONS.TRAINING_VIEW,
  PERMISSIONS.TRAINING_CREATE,
  PERMISSIONS.TRAINING_UPDATE,
  PERMISSIONS.TRAINING_DELETE,

  PERMISSIONS.SUPPLIER_VIEW,
  PERMISSIONS.SUPPLIER_CREATE,
  PERMISSIONS.SUPPLIER_UPDATE,
  PERMISSIONS.SUPPLIER_DELETE,

  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.REPORT_EXPORT,

  PERMISSIONS.AUDIT_LOG_VIEW,
  PERMISSIONS.AUDIT_LOG_CREATE,
  PERMISSIONS.AUDIT_LOG_UPDATE,
  PERMISSIONS.AUDIT_LOG_DELETE,

  PERMISSIONS.PAGEMETA_VIEW,
  PERMISSIONS.PAGEMETA_CREATE,
  PERMISSIONS.PAGEMETA_UPDATE,
  PERMISSIONS.PAGEMETA_DELETE,
  PERMISSIONS.PAGEMETA_VIEW,

  PERMISSIONS.MASTER_DATA_VIEW,
  PERMISSIONS.MASTER_DATA_CREATE,
  PERMISSIONS.MASTER_DATA_UPDATE,
  PERMISSIONS.MASTER_DATA_DELETE,
  PERMISSIONS.MASTER_DATA_STATUS_UPDATE,

  PERMISSIONS.LOCATION_VIEW,
  PERMISSIONS.LOCATION_CREATE,
  PERMISSIONS.LOCATION_UPDATE,
  PERMISSIONS.LOCATION_DELETE,
  PERMISSIONS.LOCATION_STATUS_UPDATE,

  PERMISSIONS.PRODUCT_VIEW,
  PERMISSIONS.PRODUCT_CREATE,
  PERMISSIONS.PRODUCT_UPDATE,
  PERMISSIONS.PRODUCT_DELETE,
  PERMISSIONS.PRODUCT_STATUS_UPDATE,
];

// ==========================================================
// QUALITY MANAGER
// ==========================================================

const QUALITY_MANAGER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.USER_VIEW,

  PERMISSIONS.NCR_VIEW,
  PERMISSIONS.NCR_CREATE,
  PERMISSIONS.NCR_UPDATE,
  PERMISSIONS.NCR_STATUS_UPDATE,

  PERMISSIONS.CAPA_VIEW,
  PERMISSIONS.CAPA_CREATE,
  PERMISSIONS.CAPA_UPDATE,
  PERMISSIONS.CAPA_STATUS_UPDATE,
  PERMISSIONS.CAPA_ASSIGN,

  PERMISSIONS.AUDIT_VIEW,
  PERMISSIONS.AUDIT_CREATE,
  PERMISSIONS.AUDIT_UPDATE,

  PERMISSIONS.DOCUMENT_VIEW,
  PERMISSIONS.DOCUMENT_CREATE,
  PERMISSIONS.DOCUMENT_UPDATE,
  PERMISSIONS.DOCUMENT_APPROVE,

  PERMISSIONS.TRAINING_VIEW,
  PERMISSIONS.TRAINING_CREATE,
  PERMISSIONS.TRAINING_UPDATE,

  PERMISSIONS.SUPPLIER_VIEW,
  PERMISSIONS.SUPPLIER_CREATE,
  PERMISSIONS.SUPPLIER_UPDATE,

  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.REPORT_EXPORT,

  PERMISSIONS.AUDIT_LOG_VIEW,
  PERMISSIONS.AUDIT_LOG_CREATE,
  PERMISSIONS.AUDIT_LOG_UPDATE,
  PERMISSIONS.AUDIT_LOG_DELETE,

  PERMISSIONS.PAGEMETA_VIEW,
  PERMISSIONS.PAGEMETA_CREATE,
  PERMISSIONS.PAGEMETA_UPDATE,
  PERMISSIONS.PAGEMETA_DELETE,
  PERMISSIONS.PAGEMETA_VIEW,
];

// ==========================================================
// QUALITY ENGINEER
// ==========================================================

const QUALITY_ENGINEER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.NCR_VIEW,
  PERMISSIONS.NCR_CREATE,
  PERMISSIONS.NCR_UPDATE,

  PERMISSIONS.CAPA_VIEW,
  PERMISSIONS.CAPA_CREATE,
  PERMISSIONS.CAPA_UPDATE,
  PERMISSIONS.CAPA_ASSIGN,

  PERMISSIONS.AUDIT_VIEW,

  PERMISSIONS.DOCUMENT_VIEW,

  PERMISSIONS.TRAINING_VIEW,

  PERMISSIONS.SUPPLIER_VIEW,

  PERMISSIONS.REPORT_VIEW,

  PERMISSIONS.AUDIT_LOG_VIEW,

  PERMISSIONS.PAGEMETA_VIEW,
];

// ==========================================================
// AUDITOR
// ==========================================================

const AUDITOR_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.NCR_VIEW,

  PERMISSIONS.CAPA_VIEW,

  PERMISSIONS.AUDIT_VIEW,
  PERMISSIONS.AUDIT_CREATE,
  PERMISSIONS.AUDIT_UPDATE,

  PERMISSIONS.DOCUMENT_VIEW,

  PERMISSIONS.TRAINING_VIEW,

  PERMISSIONS.SUPPLIER_VIEW,

  PERMISSIONS.REPORT_VIEW,

  PERMISSIONS.AUDIT_LOG_VIEW,

  PERMISSIONS.PAGEMETA_VIEW,
];

// ==========================================================
// EMPLOYEE
// ==========================================================

const EMPLOYEE_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.CAPA_VIEW,

  PERMISSIONS.DOCUMENT_VIEW,

  PERMISSIONS.TRAINING_VIEW,

  PERMISSIONS.REPORT_VIEW,
];

// ==========================================================
// VIEWER
// ==========================================================

const VIEWER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.NCR_VIEW,

  PERMISSIONS.CAPA_VIEW,

  PERMISSIONS.AUDIT_VIEW,

  PERMISSIONS.DOCUMENT_VIEW,

  PERMISSIONS.TRAINING_VIEW,

  PERMISSIONS.SUPPLIER_VIEW,

  PERMISSIONS.REPORT_VIEW,
];

// ==========================================================
// ROLE → PERMISSIONS
// ==========================================================

export const DEFAULT_ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: SUPER_ADMIN_PERMISSIONS,

  [ROLES.ORG_ADMIN]: ORG_ADMIN_PERMISSIONS,

  [ROLES.QUALITY_MANAGER]: QUALITY_MANAGER_PERMISSIONS,

  [ROLES.QUALITY_ENGINEER]: QUALITY_ENGINEER_PERMISSIONS,

  [ROLES.AUDITOR]: AUDITOR_PERMISSIONS,

  [ROLES.EMPLOYEE]: EMPLOYEE_PERMISSIONS,

  [ROLES.VIEWER]: VIEWER_PERMISSIONS,
};

// ==========================================================
// GET DEFAULT PERMISSIONS
// ==========================================================

export const getDefaultRolePermissions = (role) => {
  return DEFAULT_ROLE_PERMISSIONS[role] || [];
};
